<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageType>Template</PackageType>
    <PackageId>MateusDeMoura.Forge.WebApi.Templates</PackageId>
    <PackageVersion>1.0.3</PackageVersion>
    <Title>Forge Web API Templates</Title>
    <Authors>Mateus Moura</Authors>
    <Description>Template .NET para criação de APIs com Clean Architecture.</Description>
    <PackageTags>dotnet-new;templates;webapi;clean-architecture</PackageTags>
    <PackageReadmeFile>NUGET_README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Mateus-de-Moura/Forge.WebApi</RepositoryUrl>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <ContentTargetFolders>content</ContentTargetFolders>
    <EnableDefaultItems>false</EnableDefaultItems>
    <NoDefaultExcludes>true</NoDefaultExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="**/*"
             Exclude=".git/**/*;.github/**/*;.cr/**/*;.vs/**/*;**/bin/**/*;**/obj/**/*;**/*.user;.tmp-template-*/**/*;Forge.WebApi.TemplatePack.csproj;NUGET_README.md"
             Pack="true"
             PackagePath="content" />
    <None Include="NUGET_README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
